export const staydata = [
  {
    id: "1",
    beds: "2",
    city: "New Delhi",
    country: "India",
    maxGuest: "3",
    photo:
      "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?ixlib=rb-1.2.1&auto=format&fit=crop&w=2255&q=80",
    rating: "4.4",
    superHost: false,
    title: "Stylist apartment in center of the city",
    type: "Entire apartment",
  },
  {
    id: "2",
    beds: "3",
    city: "Mumbai",
    country: "India",
    maxGuest: "5",
    photo:
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80",
    rating: "4.2",
    superHost: false,
    title: "Nice apartment in center of Mumbai",
    type: "Entire apartment",
  },
  {
    id: "3",
    beds: "6",
    city: "Mumbai",
    country: "India",
    maxGuest: "10",
    photo:
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80",
    rating: "4.5",
    superHost: true,
    title: "Arty interior in 1900 wooden house",
    type: "Entire house",
  },
  {
    id: "4",
    beds: "null",
    city: "Mumbai",
    country: "India",
    maxGuest: "3",
    photo:
      "https://images.unsplash.com/photo-1556020685-ae41abfc9365?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80",
    rating: "4.48",
    superHost: false,
    title: "Apartment next to market spuare",
    type: "Entire apartment",
  },
  {
    id: "5",
    beds: "null",
    city: "New Delhi",
    country: "India",
    maxGuest: "9",
    photo:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2249&q=80",
    rating: "4.75",
    superHost: true,
    title: "Villa Aurora guest-house",
    type: "Entire house",
  },
  {
    id: "6",
    beds: "null",
    city: "Chennai",
    country: "India",
    maxGuest: "6",
    photo:
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80",
    rating: "4.95",
    superHost: true,
    title: "A cosy family house",
    type: "Entire house",
  },
  {
    id: "7",
    beds: "null",
    city: "Chennai",
    country: "India",
    maxGuest: "2",
    photo:
      "https://images.unsplash.com/photo-1505693314120-0d443867891c?ixlib=rb-1.2.1&auto=format&fit=crop&w=2591&q=80",
    rating: "4.68",
    superHost: false,
    title: "Lovely Studio near Railway Station",
    type: "Private room",
  },
  {
    id: "8",
    beds: "3",
    city: "Noida",
    country: "India",
    maxGuest: "6",
    photo:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80",
    rating: "4.12",
    superHost: false,
    title: "Peaceful little home in city center",
    type: "Entire house",
  },
  {
    id: "9",
    beds: "1",
    city: "Noida",
    country: "India",
    maxGuest: "2",
    photo:
      "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2255&q=80",
    rating: "4.49",
    superHost: false,
    title: "Beautiful new studio apartment nearby the center",
    type: "Entire apartment",
  },
  {
    id: "10",
    beds: "2",
    city: "Pune",
    country: "India",
    maxGuest: "4",
    photo:
      "https://images.unsplash.com/photo-1522156373667-4c7234bbd804?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjF9&auto=format&fit=crop&w=930&q=80",
    rating: "4.38",
    superHost: true,
    title: "Cozy woodhouse flat with wooden sauna",
    type: "Entire House",
  },
  {
    id: "11",
    beds: "3",
    city: "Pune",
    country: "India",
    maxGuest: "6",
    photo:
      "https://images.unsplash.com/photo-1494203484021-3c454daf695d?ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80",
    rating: "4.89",
    superHost: false,
    title: "Brand new studio apartment near the harbour",
    type: "Entire apartment",
  },
  {
    id: "12",
    beds: "null",
    city: "Bangalore",
    country: "India",
    maxGuest: "10",
    photo:
      "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80",
    rating: "4.63",
    superHost: false,
    title: "Beautiful and comfortable old wooden house",
    type: "Entire house",
  },
  {
    id: "13",
    beds: "3",
    city: "Bangalore",
    country: "India",
    maxGuest: "5",
    photo:
      "https://images.unsplash.com/photo-1519643381401-22c77e60520e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3MzYxfQ&auto=format&fit=crop&w=2253&q=80",
    rating: "4.24",
    superHost: false,
    title: "Bangalore Nordic Home near city cente",
    type: "Entire apartment",
  },
  {
    id: "14",
    beds: "3",
    city: "Bangalore",
    country: "India",
    maxGuest: "6",
    photo:
      "https://images.unsplash.com/photo-1523755231516-e43fd2e8dca5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1275&q=80",
    rating: "4.34",
    superHost: true,
    title: "Nice two room apartment close to everything",
    type: "Entire apartment",
  },
];
